Read Hibernate xml from a temporary file to workaround issue on reload
[17:53:17 ERROR]: [EXP]  --- Exception while trying to enable Expvp:
org.hibernate.internal.util.config.ConfigurationException: Could not access given cfg.xml URL input stream
>       at org.hibernate.boot.cfgxml.internal.ConfigLoader.loadConfigXmlUrl(ConfigLoader.java:111) ~[libhibernate-bukkit.jar:?]
>       at org.hibernate.boot.registry.StandardServiceRegistryBuilder.configure(StandardServiceRegistryBuilder.java:171) ~[libhiberna
te-bukkit.jar:?]
>       at me.minotopia.expvp.EPPlugin.initHibernate(EPPlugin.java:164) [expvp.jar:0.1.0-SNAPSHOT]
>       at me.minotopia.expvp.EPPlugin.enable(EPPlugin.java:90) [expvp.jar:0.1.0-SNAPSHOT]
>       at li.l1t.common.xyplugin.AbstractXyPlugin.onEnable(AbstractXyPlugin.java:73) [xyc.jar:4.4.2.3-SNAPSHOT]
>       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [patched.jar:git-PaperSpigot-"4c7641d"]
>       at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
>       at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
>       at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
>       at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
>       at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:769) [patched.jar:git-PaperSpigot-"4c7641d"]
>       at org.bukkit.Bukkit.reload(Bukkit.java:556) [patched.jar:git-PaperSpigot-"4c7641d"]
>       at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [patched.jar:git-PaperSpigot-"4c7641d"]
>       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [patched.jar:git-PaperSpigot-"4c7641d"]
>       at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [patched.jar:git-PaperSpigot-"4c7641d"]
>       at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629) [patched.jar:git-PaperSpigot-"4c764
1d"]
>       at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416) [patched.jar:git-PaperSpigot-"4c7641d"]
>       at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [patched.jar:git-PaperSpigot-"4c7641d"]
>       at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
>       at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.io.FileNotFoundException: JAR entry hibernate.cfg.xml not found in /home/minecraft/epqa/plugins/expvp.jar
>       at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:142) ~[?:1.8.0_92]
>       at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150) ~[?:1.8.0_92]
>       at java.net.URL.openStream(URL.java:1045) ~[?:1.8.0_92]
>       at org.hibernate.boot.cfgxml.internal.ConfigLoader.loadConfigXmlUrl(ConfigLoader.java:92) ~[libhibernate-bukkit.jar:?]
>       ... 20 more